name: Scheduled Workflow

on:
  schedule:
    - cron: '15 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Your Action
        run: |
          echo "This workflow is running at 12:10 PM Bangladesh time."
